/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "my_lib.h"

std::string demo::Greeter::greeting() {
    return std::string("Hello, World!");
}
